//! Compose-file materialization.
//!
//! Bundles a known-good docker-compose.yml at build time and writes it
//! verbatim to the instance dir on deploy. The template uses `${VAR}`
//! interpolation that compose itself resolves from the instance's `.env`
//! — so we don't do any string templating here, we just embed + write.
//!
//! Two stacks: `api` and `client`. Each lives in its own subdirectory
//! of the instance dir (`<instance>/api/` and `<instance>/client/`) so
//! they have independent `.env` + compose state and compose's
//! `COMPOSE_PROJECT_NAME` keeps the container names from colliding.
//!
//! The client stack also needs its nginx config + docker-gen upstream
//! template + initial seed file — those ship as separate templates.
//!
//! Upgrading the compose shape = cutting a new CLI release. There's no
//! runtime config to mutate; the user gets the bundled template
//! whenever the CLI is upgraded.

use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

use crate::deploy::config::Topology;

const API_COMPOSE: &str = include_str!("templates/api-compose.yml");
const API_NGINX_CONF: &str = include_str!("templates/api-nginx.conf.template");
const API_UPSTREAMS_TMPL: &str = include_str!("templates/api-upstreams.tmpl");
const API_UPSTREAMS_SEED: &str = include_str!("templates/api-upstreams.conf");
const CLIENT_COMPOSE: &str = include_str!("templates/client-compose.yml");
const CLIENT_NGINX_CONF: &str = include_str!("templates/client-nginx.conf.template");
const CLIENT_UPSTREAMS_TMPL: &str = include_str!("templates/client-upstreams.tmpl");
const CLIENT_UPSTREAMS_SEED: &str = include_str!("templates/client-upstreams.conf");

/// Write the api stack files into `<instance>/api/`:
///   - docker-compose.yml
///   - default.conf.template  (mounted into the api's nginx)
///   - upstreams.tmpl         (consumed by docker-gen)
///   - upstreams.conf         (seed; docker-gen overwrites at runtime)
///   - docker-compose.override.yml  (only for topologies where the api
///     is publicly reachable: api_only / exposed — adds a host-port
///     binding to nginx. Airgapped omits this so the api stays purely
///     internal and the stack publishes zero host ports beyond the
///     client's CLIENT_HTTP_PORT.)
pub fn write_api_stack(instance_dir: &Path, topology: Topology) -> Result<()> {
    let dir = instance_dir.join("api");
    fs::create_dir_all(&dir).with_context(|| format!("mkdir {}", dir.display()))?;
    // docker-gen writes generated/upstreams.conf via rename, which
    // requires a directory mount (not a single-file mount).
    let generated = dir.join("generated");
    fs::create_dir_all(&generated).with_context(|| format!("mkdir {}", generated.display()))?;
    fs::write(dir.join("docker-compose.yml"), API_COMPOSE)
        .with_context(|| format!("write api compose to {}", dir.display()))?;
    fs::write(dir.join("default.conf.template"), API_NGINX_CONF)
        .with_context(|| "write api nginx config")?;
    fs::write(dir.join("upstreams.tmpl"), API_UPSTREAMS_TMPL)
        .with_context(|| "write api upstreams template")?;
    fs::write(generated.join("upstreams.conf"), API_UPSTREAMS_SEED)
        .with_context(|| "write api upstreams seed")?;

    let override_path = dir.join("docker-compose.override.yml");
    match topology {
        Topology::Airgapped => {
            // Make sure no stale override from a prior topology lingers.
            let _ = fs::remove_file(&override_path);
        }
        Topology::ApiOnly | Topology::Exposed => {
            fs::write(
                &override_path,
                "# Auto-generated by glow-cli; topology requires a public api port.\n\
                 services:\n  \
                   nginx:\n    \
                     ports:\n      \
                       - \"${API_HTTP_PORT:-127.0.0.1:18081}:80\"\n",
            )
            .with_context(|| {
                format!("write api compose override to {}", override_path.display())
            })?;
        }
    }
    Ok(())
}

/// Write the client stack files into `<instance>/client/`:
///   - docker-compose.yml
///   - default.conf.template  (mounted into the client's nginx)
///   - upstreams.tmpl         (consumed by docker-gen)
///   - upstreams.conf         (seed; docker-gen overwrites at runtime)
pub fn write_client_stack(instance_dir: &Path) -> Result<()> {
    let dir = instance_dir.join("client");
    fs::create_dir_all(&dir).with_context(|| format!("mkdir {}", dir.display()))?;
    fs::write(dir.join("docker-compose.yml"), CLIENT_COMPOSE)
        .with_context(|| format!("write client compose to {}", dir.display()))?;
    fs::write(dir.join("default.conf.template"), CLIENT_NGINX_CONF)
        .with_context(|| "write client nginx config")?;
    fs::write(dir.join("upstreams.tmpl"), CLIENT_UPSTREAMS_TMPL)
        .with_context(|| "write client upstreams template")?;
    fs::write(dir.join("upstreams.conf"), CLIENT_UPSTREAMS_SEED)
        .with_context(|| "write client upstreams seed")?;
    Ok(())
}
